version: "3.7"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: editor-client-img
    container_name: editor-client
    command: npm run dev
    ports:
      - "8080:8080"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: editor-server-img
    container_name: editor-server
    command: npm run dev
    ports:
      - "3080:3080"
